version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.x
    commands:
      - echo install process started
      - npm install -f
  build:
    commands:
      - echo build process started now
      - ng build --configuration=$ENV_MODE
  post_build:
    commands:
      - echo build process finished, we should uplload to S3 now
      - cd dist/$APP_NAME
      - ls -la
      - aws s3 sync . s3://$BUCKET_NAME --delete
