version: 0.2

phases:
  install:    
    commands:
      - echo install process started
      - npm install -f && npm install -g @angular/cli
  build:
    commands:
      - echo build process started now
      - ng build --configuration=$ENV_MODE
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/$APP_NAME
    
